spring:
    application:
        name: receipt-handler
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
image:
    upload:
        dir: ${FILE_DIRECTORY}
keys:
    openai: ${OPENAI_API_KEY}
